In [33]:
import numpy as np 


In [34]:
file_path= "../data/Global_Cybersecurity_Threats_2015-2024.csv"

data = np.genfromtxt(
    file_path,
    delimiter=",",
    dtype=str,
    encoding="utf-8"

)

print(data.shape)

(3001, 10)


In [ ]:
#data headings 
data[0:1]

array([['Country', 'Year', 'Attack Type', 'Target Industry',
        'Financial Loss (in Million $)', 'Number of Affected Users',
        'Attack Source', 'Security Vulnerability Type',
        'Defense Mechanism Used', 'Incident Resolution Time (in Hours)']],
      dtype='<U35')

In [ ]:
#data selection 
data[0,2] #for selection of row and coulumns 

np.str_('Attack Type')

In [ ]:
#Attacl analysis
print(data[:,2]) #for getting every information of attack type 

['Attack Type' 'Phishing' 'Ransomware' ... 'SQL Injection' 'SQL Injection'
 'SQL Injection']


In [ ]:
#finding unique vlues 
np.unique(data[:,2])

array(['Attack Type', 'DDoS', 'Malware', 'Man-in-the-Middle', 'Phishing',
       'Ransomware', 'SQL Injection'], dtype='<U35')

In [30]:
np.size(data)

30010

In [31]:
np.unique(data[:,2], return_counts= True)

(array(['Attack Type', 'DDoS', 'Malware', 'Man-in-the-Middle', 'Phishing',
        'Ransomware', 'SQL Injection'], dtype='<U35'),
 array([  1, 531, 485, 459, 529, 493, 503]))

In [64]:
attack_types, counts= np.unique(data[1:,2], return_counts=True)
print(attack_types,counts)

['DDoS' 'Malware' 'Man-in-the-Middle' 'Phishing' 'Ransomware'
 'SQL Injection'] [531 485 459 529 493 503]


In [65]:
np.max(counts)

np.int64(531)

In [68]:
np.argmax(counts)

np.int64(0)

In [ ]:
position=" "
attack_types[position]

NameError: name 'position' is not defined

In [ ]:
#attacked country analysis
data[0,0]

np.str_('Country')

In [7]:
print(data[:,0])

['Country' 'China' 'China' ... 'Brazil' 'UK' 'Germany']


In [8]:
np.unique(data[:,0])

array(['Australia', 'Brazil', 'China', 'Country', 'France', 'Germany',
       'India', 'Japan', 'Russia', 'UK', 'USA'], dtype='<U35')

In [9]:
np.unique(data[:,0], return_counts= True)

(array(['Australia', 'Brazil', 'China', 'Country', 'France', 'Germany',
        'India', 'Japan', 'Russia', 'UK', 'USA'], dtype='<U35'),
 array([297, 310, 281,   1, 305, 291, 308, 305, 295, 321, 287]))

In [14]:
countires, counts= np.unique(data[1:,0], return_counts=True)
print(countires,counts)

['Australia' 'Brazil' 'China' 'France' 'Germany' 'India' 'Japan' 'Russia'
 'UK' 'USA'] [297 310 281 305 291 308 305 295 321 287]


In [ ]:
#targated industry analysis 
data[0,3]

np.str_('Target Industry')

In [12]:
print(data[:,3])

['Target Industry' 'Education' 'Retail' ... 'IT' 'IT' 'Retail']


In [13]:
np.unique(data[:,3])

array(['Banking', 'Education', 'Government', 'Healthcare', 'IT', 'Retail',
       'Target Industry', 'Telecommunications'], dtype='<U35')

In [15]:
np.unique(data[:,3], return_counts= True)

(array(['Banking', 'Education', 'Government', 'Healthcare', 'IT', 'Retail',
        'Target Industry', 'Telecommunications'], dtype='<U35'),
 array([445, 419, 403, 429, 478, 423,   1, 403]))

In [17]:
industry_type, counts= np.unique(data[1:,3], return_counts=True)
print(industry_type,counts)

['Banking' 'Education' 'Government' 'Healthcare' 'IT' 'Retail'
 'Telecommunications'] [445 419 403 429 478 423 403]


In [10]:
#financial loss analysis 
data[0,4]

np.str_('Financial Loss (in Million $)')

In [15]:
data[1:,4]

array(['80.53', '62.19', '38.65', ..., '32.97', '32.17', '48.2'],
      shape=(3000,), dtype='<U35')

In [16]:
type(data[1,4])

numpy.str_

In [20]:
financial_loss=data[1:,4].astype(float)
type(financial_loss[0]) 

numpy.float64

In [21]:
np.max(financial_loss)

np.float64(99.99)

In [24]:
np.min(financial_loss)

np.float64(0.5)

In [25]:
np.sum(financial_loss)

np.float64(151478.91)

In [28]:
#security analysis 
data[0:,8]

array(['Defense Mechanism Used', 'VPN', 'Firewall', ...,
       'AI-based Detection', 'Firewall', 'VPN'],
      shape=(3001,), dtype='<U35')

In [37]:
np.unique(data[0:,8])

array(['AI-based Detection', 'Antivirus', 'Defense Mechanism Used',
       'Encryption', 'Firewall', 'VPN'], dtype='<U35')

In [38]:
np.unique(data[0:,8], return_counts= True)

(array(['AI-based Detection', 'Antivirus', 'Defense Mechanism Used',
        'Encryption', 'Firewall', 'VPN'], dtype='<U35'),
 array([583, 628,   1, 592, 585, 612]))

In [43]:
defence_mechanism_used= data[0:,8]

In [44]:
defence_mechanism_used, counts= np.unique(data[1:,8], return_counts=True)
print(defence_mechanism_used,counts)

['AI-based Detection' 'Antivirus' 'Encryption' 'Firewall' 'VPN'] [583 628 592 585 612]


In [45]:
np.max(counts)

np.int64(628)

In [46]:
np.argmax(counts)

np.int64(1)

In [51]:
#security vulneribilty analysis 
data[0,7]

np.str_('Security Vulnerability Type')

In [52]:
data[0:,7]

array(['Security Vulnerability Type', 'Unpatched Software',
       'Unpatched Software', ..., 'Weak Passwords', 'Unpatched Software',
       'Zero-day'], shape=(3001,), dtype='<U35')

In [53]:
np.unique(data[0:,7])

array(['Security Vulnerability Type', 'Social Engineering',
       'Unpatched Software', 'Weak Passwords', 'Zero-day'], dtype='<U35')

In [56]:
security_vulnerbilty_type , counts = np.unique(data[0:,7], return_counts= True)
print(security_vulnerbilty_type, counts)

['Security Vulnerability Type' 'Social Engineering' 'Unpatched Software'
 'Weak Passwords' 'Zero-day'] [  1 747 738 730 785]


In [60]:
np.max(counts)

np.int64(785)

In [61]:
np.argmax(counts)

np.int64(4)